manifest:
  version: "1.2"

  self:
    path: hmi_app

  remotes:
    - name: origin
      url-base: https://github.com/JaagupAverin
  defaults:
    remote: origin
    revision: main

  projects:
    - name: gale-shared
      path: shared
      import: true
