manifest:
  version: "1.2"

  self:
    path: gale_hmi_app

  remotes:
    - name: origin
      url-base: https://github.com/JaagupAverin

  projects:
    - name: gale-shared
      path: gale_shared
      remote: origin
      revision: main
      import: true
